---

#__bootstrap_pip__python_executable_default: "python3.10"
#__bootstrap_pip__python_executable_default: "python3"
__bootstrap_pip__python_executable_default: "{{ ansible_python_interpreter }}"
__bootstrap_pip__python_executable: "{{ bootstrap_pip__python_executable | d(__bootstrap_pip__python_executable_default) }}"

__bootstrap_pip__pip_executable_default: pip3
__bootstrap_pip__pip_executable: "{{ bootstrap_pip__pip_executable | d(__bootstrap_pip__pip_executable_default) }}"

__bootstrap_pip__pip_version_default: latest
__bootstrap_pip__pip_version: "{{ bootstrap_pip__pip_version | d(__bootstrap_pip__pip_version_default) }}"

__bootstrap_pip__log_prefix_get_pip_version: get-pip-version |
__bootstrap_pip__log_prefix_get_pip: run-get-pip |
__bootstrap_pip__log_prefix_pipenv: Install Pip Libs | Pip ENV=>[{{ __bootstrap_pip_env.name }}] |

bootstrap_pip__env_force_rebuild: true
#bootstrap_pip__env_force_rebuild: no

__bootstrap_pip__env_list__default:
  - pip_executable: "{{ __bootstrap_pip__pip_executable }}"
    version: latest
#  - pip_executable: "{{ __bootstrap_pip__pip_executable }}"
#    version: latest
#    libraries:
#      - docker
#      - docker-compose
#  - virtualenv: "{{ '~/.venv/ansible' | expanduser }}"
##    virtualenv_command: "python3 -m venv"
#    libraries:
#      - ansible

bootstrap_pip__packages:
  - python3
  - python3-pip
  - python3-virtualenv
  - python3-cryptography

bootstrap_pip__environment_vars:
  SETUPTOOLS_USE_DISTUTILS: stdlib
  ## setting following env vars solves the problem:
  ## UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 117: ordinal not in range(128)
  ## ref: https://github.com/pypa/pip/issues/10219
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8
#  PATH: "$PATH:/usr/local/bin"

__bootstrap_pip__environment_ignore_root_user_action:
  ## ref: https://github.com/pypa/pip/pull/10990#issuecomment-1091476480
  #PIP_NO_WARN_ABOUT_ROOT_USER: 0
  ## ref: https://github.com/pypa/pip/issues/11179#issuecomment-1152766374
  ## or use `--root-user-action ignore` option in each pip command
  PIP_ROOT_USER_ACTION: ignore
  ## setting following env vars solves the problem:
  ## UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 117: ordinal not in range(128)
  ## ref: https://github.com/pypa/pip/issues/10219
  LANG: en_US.UTF-8
  LC_ALL: en_US.UTF-8

bootstrap_pip__config_dir: "{{ ansible_env.HOME }}/.config/pip"

bootstrap_pip__lib_state: present
bootstrap_pip__lib_priority_default: 100

__bootstrap_pip__libs_default:
  - name: setuptools
    priority: 1
  - pyyaml
  - jinja2
  - cryptography
  #  - pyOpenSSL
  - requests
  - netaddr
  - passlib
  - jsondiff
#  - firewall

__bootstrap_pip__libs: "{{ bootstrap_pip__libs | d(__bootstrap_pip__libs_default)|d([]) }}"

__bootstrap_pip__tmp: /tmp

__bootstrap_pip__get_pip_url: https://bootstrap.pypa.io/get-pip.py

__bootstrap_pip__python_interpreter_default: "{{ ansible_python_interpreter | d(discovered_interpreter_python) }}"
__bootstrap_pip__python_interpreter: "{{ bootstrap_pip__python_interpreter | d(__bootstrap_pip__python_interpreter_default) }}"

__bootstrap_pip__virtualenv_command_default: "{{ __bootstrap_pip__python_interpreter }} -m venv"
__bootstrap_pip__virtualenv_command: "{{ bootstrap_pip__virtualenv_command | d(__bootstrap_pip__virtualenv_command_default) }}"

__bootstrap_pip__system_pip_upgrade_enabled_default: true
__bootstrap_pip__system_pip_upgrade_enabled: "{{ bootstrap_pip__system_pip_upgrade_enabled | d(__bootstrap_pip__system_pip_upgrade_enabled_default) }}"
